AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: upload_lambda.lambda_handler
      Runtime: python3.10
      CodeUri: backend/
      Environment:
        Variables:
          S3_BUCKET: your-bucket-name
      Events:
        UploadApi:
          Type: Api
          Properties:
            Path: /upload
            Method: post

  ExtractFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: extract_lambda.lambda_handler
      Runtime: python3.10
      CodeUri: backend/
      Environment:
        Variables:
          S3_BUCKET: your-bucket-name
      Events:
        ExtractApi:
          Type: Api
          Properties:
            Path: /extract
            Method: post

  SummariseFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: summarise_lambda.lambda_handler
      Runtime: python3.10
      CodeUri: backend/
      Environment:
        Variables:
          S3_BUCKET: your-bucket-name
      Events:
        SummariseApi:
          Type: Api
          Properties:
            Path: /summarise
            Method: post